### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by caniszczyk**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/pr-bot/2)

### CODE REVIEW

**Comment by caniszczyk** [comment]
Hey @foxish, so I have the CLA bot connected now and working for the repo.

**Comment by foxish** [comment]
Thanks @caniszczyk. It seems to be working as expected! I can use this repo as a base and get our bot to recognize that cla status and post a message and apply a label. 
Are there any major changes coming, in the effort that was ongoing to switch to webhooks? Is this working on polling at this time?

**Comment by bgrant0607** [comment]
Great!

**Comment by caniszczyk** [comment]
@foxish I'll have to defer to @emsearcy on progress, I know there's been some work on what was discussed in the previous github issue

**Comment by foxish** [comment]
It is interesting that the Google CLA bot did not apply the cla:yes/no label here. 
Is that because the labels don't exist, or because we didn't mark  cla/google as a 'required' status?

**Comment by willnorris** [comment]
It's because the labels don't exist (https://github.com/kubernetes/pr-bot/labels)

**Comment by foxish** [comment]
@willnorris Thanks for clarifying.

**Comment by willnorris** [comment]
I would also recommend that the LF CLA bot use something like "cla/linuxfoundation" as the context rather than just "cla" to ensure there's never any conflict.  That's the pattern I picked up from Travis CI and others and have been using for the Google CLA bot.

**Comment by caniszczyk** [comment]
Thanks @willnorris we will fix this today

**Comment by foxish** [comment]
@caniszczyk Before we start on implementing the label behavior in our bot, I'd like to discuss some aspects of your system to understand how they might work after we switch to the CNCF bot.

1. When no CLA is found, we apply the `cla: no` label and wait for the person to sign and comment back with `I signed it!`. 
   * Can we expect the `cla/linuxfoundation` status on the PR to change in response to a new comment? (see https://github.com/kubernetes/kubernetes.github.io/pull/627#issuecomment-224343760)
   * What are the things that would trigger a re-evaluation of the CLA status? Does it happen on every update to the PR?

2.  Is it possible to figure out from the status if there are multiple commits in a PR from different authors?
   * In case of this, we typically want to post a different comment to the PR, based on whether all authors have signed the CLA (see https://github.com/kubernetes/kubernetes/pull/30923#issuecomment-240851256), or not.

**Comment by test-foxish** [comment]
Labelling this PR as size/XS

**Pull request closed without merging**
